name: flutter_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_blue_plus: ^1.31.15
  permission_handler: ^8.1.6
  flutter_secure_storage: ^5.0.2
  firebase_database: ^10.4.11
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  camera: ^0.10.5+9
  dio: ^5.4.2+1
  firebase_messaging: ^14.8.2
  firebase_analytics: ^10.10.2
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.9
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
