// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMjF3qr9i-OM5T-n3hcTK2qSWH_APNGM',
    appId: '1:356571080419:android:ed7d4c986a32129abbc7d6',
    messagingSenderId: '356571080419',
    projectId: 'sol-fyp',
    databaseURL: 'https://sol-fyp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sol-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-17SO8eFSq9POUfF2kh4INsBWCkijiyM',
    appId: '1:356571080419:ios:f00c4dd43207f56bbbc7d6',
    messagingSenderId: '356571080419',
    projectId: 'sol-fyp',
    databaseURL: 'https://sol-fyp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sol-fyp.appspot.com',
    androidClientId: '356571080419-6hqv6i1b8uisvnb6u2kqu9gtfj9a4srk.apps.googleusercontent.com',
    iosClientId: '356571080419-8g7ubk5uqplsmv0oh344294844d8167l.apps.googleusercontent.com',
    iosBundleId: 'com.shollingsworth.PetalMinder',
  );
}
